id: IF65DFF42
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:56:46+00:00'
last_modified: '2022-06-10T08:45:35.701712+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W15588
  title: ཡན་ལག་བརྒྱད་པའི་སྙིང་པོ་བསྡུས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8CDD:
      image_group_id: I1PD382
      title: Volume 1 of yan lag brgyad pa'i snying po bsdus pa
      total_pages: 528
      order: 1
      base_file: 8CDD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
